# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: New York Pokemon Go
email: info@newyorkpokemongo.com
description: Domain available
url: http://newyorkpokemongo.com

# Meta variable for Google Webmaster tools
google-verification: yLu0PXM6C9JSnbhNX24jf4tDg9FbiqtlYbt1Ubf1g9A

exclude:
    - LICENSE
    - README.md
    - CNAME
    - archive

# Build settings
markdown: kramdown
highlighter: rouge
